# Generated by Django 5.2.4 on 2025-07-31 16:22

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktmpropertyhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='facilities',
            field=models.ManyToManyField(blank=True, help_text='Select the available facilities from the predefined list.', to='ktmpropertyhub.facility'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='other_facilities',
            field=models.TextField(blank=True, help_text='Enter any additional facilities that are not in the list, separated by commas (e.g. Rooftop Garden, Servant Quarters).', null=True),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, help_text='An optional caption for the image.', max_length=255, null=True)),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Is this the main display image for the property?')),
                ('property_listing', models.ForeignKey(help_text='The property this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ktmpropertyhub.propertylisting')),
            ],
        ),
    ]
