# Generated by Django 5.2.4 on 2025-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktmpropertyhub', '0002_seed_states_districts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylisting',
            old_name='rent_duration_value',
            new_name='aana',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='land_size_1_unit',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='land_size_1_value',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='land_size_2_unit',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='land_size_2_value',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='other_facilities',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='rent_duration_unit',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='rent_period',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='bigha',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='built_up_area_min_sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum built-up area in square feet', null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='built_up_area_sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Built-up area in square feet', null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='dam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='dhur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='frequency',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Per Month'), ('YEARLY', 'Per Year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='katha',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='paisa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='rent_available_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent Available Duration'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='rent_available_duration_unit',
            field=models.CharField(blank=True, choices=[('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='ropani',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='total_land_area_sqft',
            field=models.FloatField(blank=True, help_text='Total land area in square feet, calculated automatically.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='common_bathrooms_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum common bathrooms.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='common_bedrooms_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum common bedrooms.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='floors_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum floors', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='kitchens_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum kitchens.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='living_rooms_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum living rooms.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='master_bedrooms_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum master bedrooms.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='parking_bike_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum bike parking.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='parking_car_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum car parking.', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minium price of the property.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='road_size_min_ft',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum size of the road.', null=True),
        ),
    ]
